language: c

before_install:
  - "export ARDUINO_VER=1.8.5"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - wget http://downloads.arduino.cc/arduino-$ARDUINO_VER-linux64.tar.xz
  - tar xf arduino-$ARDUINO_VER-linux64.tar.xz
  - sudo mv arduino-$ARDUINO_VER /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/AABlink
  
script:
  - arduino --verify --board arduino:avr:uno $PWD/examples/FadeNBlink/FadeNBlink.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/QuickFade/QuickFade.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/ShortFlash/ShortFlash.ino
